learning_users/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from user_account import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_account/', include('user_account.urls')),
    path('', views.index, name='index'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

learning_users/learning_users/user_account/urls.py
from django.urls import path
from user_account import views

#TEMPLATES URLs

app_name = 'user_account'

urlpatterns=[
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
]

learning_users/learning_users/user_account/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



class UserProfileInfo(models.Model):
    User.username = models.CharField(max_length=264, )
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/learning_users/user_account/forms.py
from django import forms
from django.contrib.auth.models import User
from user_account.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/learning_users/user_account/views.py
from django.shortcuts import render
from user_account.forms import UserForm,UserProfileInfoForm

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'user_account/index.html')


@login_required
def special(request):
    returnHttpResponse("You are logged in, Nice!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm

    return render(request, 'user_account/registration.html',
                            {'user_form':user_form,
                              'profile_form':profile_form,
                              'registered':registered,})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'user_account/login.html')

learning_users/learning_users/templates/user_account/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title></title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <!-- <link href='{% static "img/apple-touch-icon.png" rel="icon" %}'> -->
    <!-- <link href='{% static "img/apple-touch-icon.png" rel="apple-touch-icon" %}'> -->


    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'vendor/animate.css/animate.min.css' %}">
    <link rel="stylesheet" href='{% static 'vendor/aos/aos.css' %}'>
    <link rel="stylesheet" href='{% static 'vendor/bootstrap/css/bootstrap.min.css' %}'>
    <link rel="stylesheet" href='{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}'>
    <link rel="stylesheet" href='{% static 'vendor/boxicons/css/boxicons.min.css' %}'>
    <link rel="stylesheet" href='{% static 'vendor/glightbox/css/glightbox.min.css'  %}'>
    <link rel="stylesheet" href='{% static 'vendor/remixicon/remixicon.css' %}'>
    <link rel="stylesheet" href='{% static 'vendor/swiper/swiper-bundle.min.css' %}'>

    <!-- Template Main CSS File -->
    <link rel="stylesheet" href='{% static 'css/stylecss.css' %}'>

    <!-- =======================================================
    * Template Name: templates inherit
    * Template URL: https://bootstrapmade.com/company-free-html-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
  </head>
  <body>
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
      <div class="container d-flex align-items-center">

     <!--   <h1 class="logo me-auto"><a href="index.html"><span>Com</span>pany</a></h1> -->
        <!-- Uncomment below if you prefer to use an image logo -->
         <a href="index.html" class="logo me-auto "><img src="assets/img/logo.png" alt="" class="img-fluid"></a>
        <nav id="navbar" class="navbar position-left order-last order-lg-0">
          <ul>
            <li><a href="{% url 'index' %}" class="active">Home</a></li>
            <li><a href="{% url 'admin:index' %}">Admin</a></li>

            {% if user.is_authenticated %}
              <li>  <a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
              <li> <a href="{% url 'user_account:user_login' %}">Login</a> </li>
              <li><a href="{% url 'user_account:register' %}">Register</a></li>
            {% endif %}

          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
      </div>
    </header>
    <!-- End Header -->
    <div id="topspace2">

    </div>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>
      <!-- ======= Footer ======= -->
      <footer id="footer">

        <div class="footer-top">
          <div class="container">
            <div class="row">

              <div class="col-lg-3 col-md-6 footer-contact">
                <h3>Services Clever Fast</h3>
                <p>
                  145 AVENUE CHARLEX ROUXEL PONTAULT COMBALT<br>
                  ILE DE FRANCE 77340<br>
                  France <br><br>
                  <strong>Phone:</strong> +33 749032221<br>
                  <strong>Email:</strong> scleverfast@gmail.com<br>
                </p>
              </div>

              <div class="col-lg-2 col-md-6 footer-links">
                <h4>Links</h4>
                <ul>
                <li><i class="bx bx-chevron-right"></i><a href="index.html" class="active">Home</a></li>
              <li><i class="bx bx-chevron-right"></i><a href="la-societe.html">la societe</a></li>
              <li><i class="bx bx-chevron-right"></i><a href="nos-savoir-faire.html">Nos savoir faire</a></li>
              <li><i class="bx bx-chevron-right"></i><a href="rejoignez-nous.html">Rejoignez nous</a></li>
                </ul>
              </div>

              <div class="col-lg-3 col-md-6 footer-links">
              </div>

              <div class="col-lg-4 col-md-6 footer-newsletter">
                <h4>Si vous avez les qualifications rejoignez-nous, maintenant!</h4>
                  <a href="rejoignez-nous.html" class="btn-get-started">REJOIGNEZ NOUS</a>
              </div>
            </div>
          </div>
        </div>

        <div class="container d-md-flex py-4">

          <div class="me-md-auto text-center text-md-start">
            <div class="copyright">
              &copy; Copyright <strong><span>ServiceCleverFast</span></strong>. All Rights Reserved
            </div>

          </div>
        </div>
      </footer><!-- End Footer -->

      <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

      <!-- Vendor JS Files -->
      <script src='{% static 'vendor/aos/aos.js' %}'></script>
      <script src='{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}'></script>
      <script src='{% static 'vendor/glightbox/js/glightbox.min.js' %}'></script>
      <script src='{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}'></script>
      <script src='{% static 'vendor/php-email-form/validate.js' %}'></script>
      <script src='{% static 'vendor/swiper/swiper-bundle.min.js' %}'></script>
      <script src='{% static 'vendor/waypoints/noframework.waypoints.js' %}'></script>
      <!-- BOOTSTRAPJAVA ONLINE -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

learning_users/learning_users/templates/user_account/index.html
{% extends "user_account/base.html" %}
{% block body_block %}

  <div class="jumbotron">
    <h1>Django Level Five</h1>
  </div>

{% endblock %}

learning_users/learning_users/templates/user_account/login.html
{% extends 'user_account/base.html' %}
{% block body_block %}

  <div class="jumbotron">
    <h1>Login:</h1>
    <form action="{% url 'user_account:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="enter username">

      <label for="password">Password:</label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">

    </form>

  </div>


{% endblock %}

learning_users/learning_users/templates/user_account/registration.html
{% extends "user_account/base.html" %}

{% load static %}

{% block body_block %}

  <div class="jumbotron">
    <h1>Django Level Five</h1>
    {% if registered %}
      <h1>thank you for registering!</h1>
    {% else %}
      <h1>Register Here!</h1>
      <h3>Fill out the form:</h3>

      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>
      {% endif %}

  </div>

{% endblock %}